### ISSUE TITLE
Flip view for N64 and PS2

### ISSUE THREAD

**Issue by getupor** [Duimon/Duimon-Mega-Bezel-Potato-21x9#1]
Hello Duimon

I got a feedback from user who got the picture mirrored while using the N64 and PS2 preset.

![N64](https://github.com/user-attachments/assets/0738b7cc-ddba-42a0-b3dc-d11a9a2ae298)
![PS2](https://github.com/user-attachments/assets/1ec4a749-b4ec-4f01-8c1a-ef8b6fb7f00f)

While trying to use flip setting, the game appear correct, but then it's the background that is reversed.

Is there a setting to solve that ?
With HSM, i was using the `HSM_FLIP_VIEWPORT_VERTICAL = "1.000000"` line, but i don't know if it don't works (or if I put it on the wrong place).

**Comment by Duimon** [comment]
The flipping should only occur when using the opengl video driver, Switch to the Parallel-RDP RDP plugin and use Vulkan.

In any case the Mega Bezel has built-in wildcards for every hardware accelerated core so this shouldn't happen. Make sure you are using the newest version of the Mega Bezel standard release. (It is be the same as what is provided if you update your slang shaders inside retroarch.

As a last resort there are parameters for flipping both the screen and the viewport. Some combination of the two will fix it.
